### ISSUE TITLE
Tracking item: List of changes to be made in Version 1.1 of the API Definition

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/mojaloop-specification#52] opened 2020-02-24 16:04 UTC
## Current list of items for v1.1 of the Mojaloop FSPIOP API

| S.No | Type | Title | Link | Notes |
| --- | --- | --- | --- | --- |
| 1 | Change Request | Possibility to notify Payee FSP on successful commit in Switch | https://github.com/mojaloop/mojaloop-specification/issues/29 | Finalized |
| 2 | Bug | Incorrect use of Unicode encoded equals sign ('\u003d' instead of '=') in the end-to-end example | https://github.com/mojaloop/mojaloop-specification/issues/31 | |
| 3 | Bug | Describe quote rejection for Payer initiated transaction in API Definition document | https://github.com/mojaloop/mojaloop-specification/issues/43 | |
| 4 | Change Request | Clarify usage of "ABORTED" transfer state in a PUT /transfers/{ID} | https://github.com/mojaloop/mojaloop-specification/issues/47 | |
| 5 | Clarification needed | Interpretation of the Data Model for the ExtensionList element | https://github.com/mojaloop/mojaloop-specification/issues/51 | |
| 6 | Change Request | ~Linking quotes and transfers using transactionId from quote Object~ | - | Upon Review - this is a breaking change, so a candidate for v2.0 (Need an issue on GitHub proposed in the old word format) |
| 7 | Change Request | Clarity on whether or not padding is required while Base64URL Encoding | https://github.com/mojaloop/mojaloop-specification/issues/16 | - |Need to agree whether this needs to go in the Spec or the new "Implementation guide" |
| 8 | Solution Proposal | Use of case-insensitive HTTP headers in API Signature | - | Changes to API Definition, Signature docs; Already **accepted** by the CCB; Need to create an issue on GitHub for visibility |
| 9 | Solution Proposal | Clarify usage of FSPIOP-Destination in GET /parties | - | Changes to API Definition, Signature docs; Mostly **accepted** by the CCB; Need to create an issue on GitHub for visibility |
| 10 | Change Request | Change Request: Adding ExtensionList fields to existing data structures | #30 | Mostly **accepted** by the CCB for 'PartyIdInfo' Object |

**Comment by elnyry** [comment] 2020-04-06 23:22
The current drafts for v1.1 are below; once these are agreed, I'll create markdown versions (markup used to show changes).
1. [API Definition_v1.1-draft_Updated-2020-04-07.docx](https://github.com/mojaloop/mojaloop-specification/files/4441231/API.Definition_v1.1-draft_Updated-2020-04-07.docx)
2. [Signature_v1.1-draft_Updated-2020-04-07.docx](https://github.com/mojaloop/mojaloop-specification/files/4441232/Signature_v1.1-draft_Updated-2020-04-07.docx)
3. [FSPIOP-OpenAPI-v1.1-yaml.txt](https://github.com/mojaloop/mojaloop-specification/files/4441239/FSPIOP-OpenAPI-v1.1-yaml.txt) <-- Rename to .yaml



Reference: [Solution Proposal 12 - Clarify usage of FSPIOP-Destination.docx](https://github.com/mojaloop/mojaloop-specification/files/4441233/Solution.Proposal.12.-.Clarify.usage.of.FSPIOP-Destination.docx)

**Comment by elnyry** [comment] 2020-04-07 10:13
I've struck-off #6 above as it is a breaking change if we're adding a 'required' element to the Data model (adding 'quoteId' or 'transactionId' to the transfer message to help linking quotes and transfers).

However, if we have the solution proposal accepted, it will be an item for v2.0

**Comment by elnyry** [comment] 2020-04-09 13:18
@millerabel, @matthewbohan, @ehenrka , @rjpwip, @Mutashobya, @jmssebunnya , @MichaelJBRichards, @ritviksinha, @hill-chen-hw, @DrRayCUI 

As we discussed on the CCB meeting on April 7th 2020, here's the current proposal that the attendees agreed to:

1. Review the current drafts for **v1.1** (in the above comments) - The CCB members to review and respond in two weeks time, i,e., by the time of the next CCB meeting
2. Address the feedback, make changes as necessary
3. If its agreed by the CCB, then publish drafts to the public and announce a 2-week period for comments and feedback
4. After the above two weeks, make an official v1.1 Release once any feedback, issues reported are addressed.
5. Changes requested after the couple of weeks, should be put in backlog for either 1.2 or 2.0 based on the change requested.

For those of you who were able to make it to the last meeting (@matthewbohan , @ehenrka , @rjpwip , @MichaelJBRichards , @DrRayCUI ), thank you and look forward to your inputs.

For those of you who couldn't make it - @Mutashobya , @jmssebunnya, @ritviksinha  - we need your input on this, at the very least, a 'yay' vote and if its a 'nay' for any issue, then the reasoning for that. A 'nay' without a reason / justification, is not valid.

**Comment by elnyry** [comment] 2020-04-15 10:47
Updated drafts for v1.1: 
- This one has markup for **all** the changes[API Definition_v1.1-draft_Updated-2020-04-15.docx](https://github.com/mojaloop/mojaloop-specification/files/4480585/API.Definition_v1.1-draft_Updated-2020-04-15.docx)
- draft with markup enabled for content changes only - [API Definition_v1.1-draft_Updated-2020-04-15-MarkupForContentChangesOnly.docx](https://github.com/mojaloop/mojaloop-specification/files/4480716/API.Definition_v1.1-draft_Updated-2020-04-15-MarkupForContentChangesOnly.docx)

**Comment by ehenrka** [comment] 2020-04-19 19:03
Section 1.2 (Document Version Information) needs to be updated with other changes than the ones I had prepared for version 1.1.

**Comment by elnyry** [comment] 2020-04-23 20:07
Thanks Henrik.

Here's the updated draft with the description of changes: [API Definition_v1.1-draft_Updated-2020-04-24.docx](https://github.com/mojaloop/mojaloop-specification/files/4524943/API.Definition_v1.1-draft_Updated-2020-04-24.docx)

**Comment by ehenrka** [comment] 2020-04-28 13:45
Thanks Sam,

Some minor comments regarding the document version information section:

- The "1." in the change description column is larger than all the other text.
- The date in the document version information table for version 1.1 says "2020-01-16" instead of "2020-04-14" as in the footer.

Apart from the above, in the Introduction (Section 2) it currently says "Version 1.0 of the API is designed to be used within a country or region; ...". The "Version 1.0" should probably say "Version 1.x" instead to include version 1.1 as well.

**Comment by elnyry** [comment] 2020-04-28 19:30
Nice catch Henrik - @ehenrka .. Thank you!

Updated draft here with the 3 changes: [API Definition_v1.1-draft_Updated-2020-04-29.docx](https://github.com/mojaloop/mojaloop-specification/files/4548068/API.Definition_v1.1-draft_Updated-2020-04-29.docx)

**Comment by matthewbohan** [comment] 2020-05-05 22:54
I vote yes for this set of changes as v1.1, thanks!

**Comment by jmssebunnya** [comment] 2020-05-07 11:22
I have reviewed the changes and fine with them. Yes Vote

**Comment by ritviksinha** [comment] 2020-05-19 13:48
I have reviewed the changes along with my technical implementation team. I vote Yes for v1.1 changes.

**Comment by rjpwip** [comment] 2020-05-19 14:18
Yes vote from me.

**Comment by elnyry** [comment] 2020-06-02 10:59
Thanks everyone! This has been confirmed on the CCB call on May 19th 2020.

**Comment by ehenrka** [comment] 2021-01-11 14:53
Closing this issue as version 1.1 of the API has been released.

**Closed by ehenrka** 2021-01-11 14:53 UTC
Labels: fspiop-change-request
